DROP TABLE IF EXISTS orders;

CREATE TABLE orders (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  status TINYINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL,
  amount_cents INT UNSIGNED NOT NULL,
  payload VARCHAR(512) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB;
